### ISSUE TITLE
Misleading install print

### ISSUE THREAD

**Issue by Winterhuman** [n0-computer/beetle#87]
When installing, it always prints:

```
iroh was installed successfully to /home/user/.config/iroh/bin/iroh
  export IROH_INSTALL="/home/user/.config/iroh"
  export PATH="$IROH_INSTALL/bin:$PATH"
Run '/home/user/.config/iroh/bin/iroh --help' to get started
```

However, doing the install will move the binaries to `~/.local/bin` or `/usr/local/bin` (for normal users and root respectively), the message doesn't change to reflect this. (As a side note, when does it install to `~/.config/iroh/bin`? `sudo` or not, it never seems to keep binaries there)

**Comment by Arqu** [comment]
And the relevant new ones have it fixed too :)
